[project]
name = "mcu-pico"
version = "0.1.0"
description = "Micropython docs and scripts for Raspberry Pi Pico"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.ruff]
lint.ignore = ["F401"] # Ignore unused imports
